name: Build zip and set to release

on: 
  push:
    tags:
    - '*'

env:
  AZURE_FUNCTIONAPP_NAME: microsoft-purview-business-intelligence # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'   # set this to the path to your web app project, defaults to the repository root

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub action'
      uses: actions/checkout@v2

    - name: Zip everything
      run: zip -r release.zip * .*

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "release.zip"
        omitBody: true
